server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA : toutes les routes redirigées vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers auth-service
    location /api/auth {
        proxy_pass http://auth-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers product-service
    location /api/products {
        proxy_pass http://product-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/cart {
        proxy_pass http://product-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers order-service
    location /api/orders {
        proxy_pass http://order-service:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}